@address= http://localhost:5056
@toDoTaskId = b7d45e37-f220-4d08-8ad6-12d05e54f052
@pageNumber = 4
@pageSize = 5

###
GET {{address}}/to-do-tasks/{{toDoTaskId}}

###
GET {{address}}/to-do-tasks?pageNumber={{pageNumber}}&pageSize={{pageSize}}

###
GET {{address}}/to-do-tasks/incoming?incomingFilter=2
###
POST {{address}}/to-do-tasks
Content-Type: application/json

{
  "expirationDate" : "2025-05-13T19:00:00.000Z",
  "title": "Title Today Tomorrow",
  "description": "Description Today",
  "percentComplete": 50
}

###
PUT {{address}}/to-do-tasks/{{toDoTaskId}}
Content-Type: application/json

{
  "expirationDate" : "2025-05-10",
  "title": "Update Title 123",
  "description": "Updated Description",
  "percentComplete": 60
}

###
PATCH {{address}}/to-do-tasks/{{toDoTaskId}}/percent-complete
Content-Type: application/json

{
  "percentComplete": 40
}

###
DELETE {{address}}/to-do-tasks/{{toDoTaskId}}

###
PATCH {{address}}/to-do-tasks/{{toDoTaskId}}/done
