@address= http://localhost:5056
@toDoTaskId = 355a3bd4-8936-4c28-ac7c-7bf300799d63
@pageNumber = 1
@pageSize = 5

###
GET {{address}}/to-do-tasks/{{toDoTaskId}}

###
GET {{address}}/to-do-tasks?searchPhrase=New&pageNumber={{pageNumber}}&pageSize={{pageSize}}

###
GET {{address}}/to-do-tasks?searchPhrase=New&pageNumber={{pageNumber}}&pageSize={{pageSize}}&sortBy=ExpirationDate&sortDirection=Descending

###
GET {{address}}/to-do-tasks/incoming?incomingFilter=Today

###
POST {{address}}/to-do-tasks
Content-Type: application/json

{
  "expirationDate" : "2025-05-31T19:00:00.000Z",
  "title": "Title Today New",
  "description": "Description Today New",
  "percentComplete": 33
}

###
PUT {{address}}/to-do-tasks/{{toDoTaskId}}
Content-Type: application/json

{
  "expirationDate" : "2025-06-10",
  "title": "Update Title New",
  "description": "Updated Description",
  "percentComplete": 70
}

###
PATCH {{address}}/to-do-tasks/{{toDoTaskId}}/percent-complete
Content-Type: application/json

{
  "percentComplete": 85
}

###
DELETE {{address}}/to-do-tasks/{{toDoTaskId}}

###
PATCH {{address}}/to-do-tasks/{{toDoTaskId}}/done
